[tools]
go                       = "latest"
golangci-lint            = "2.8.0"
golangci-lint-langserver = "latest"
goreleaser               = "latest"
just                     = "latest"
markdownlint-cli2 = "latest"
pre-commit               = "latest"
python                   = "3.14"
