[tools]
bun                      = "latest"
go                       = "latest"
golangci-lint            = "latest"
golangci-lint-langserver = "latest"
goreleaser               = "latest"
just                     = "latest"
markdownlint-cli2 = "latest"
pre-commit               = "latest"
python                   = "latest"
